title: Samuel Fernando
position: Quantum & Data Engineer
affiliation: Blueshift Brasil
email: samuel.silva@blueshift.com.br
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?hl=en&user=chszpPcAAAAJ
github_link: https://github.com/samuelfernandofs
linkedin: https://www.linkedin.com/in/samuelfernando2030/
avatar: https://lh3.googleusercontent.com/30qfxd1kbONgXi6nlJxYlcPAc56eql7U-qWh4lKj-mg5XEA_HaBvMqEVNaCANNM45H2StenFKWtZs0H7cq5Ro0twYBIopzIPO6Q3bdeW52aKBD7pJJeKDAVHM6qgS2965TfGjxa4ZQfgs8xq7G0jQdkmV-t1oAltyDoJ2rsCZwgVbgY16UZ0L4V959Fb7LpWgnUwC7pMlbAt6CwLwuKrULBN6e7rV56trfJkVNSPI5ITXD7v3NthVVBzw_D9VuiX3Ivi3_KyVajNAhmQXlkX-Tzqe-PuA_OZg30lYyGwMrdiczgLfMgL7sMn3GfzVARueGLo5veZTdWXDy-ISD4282gXyvL33Urk1xtWSfaPucT7tW8jC4i5Wx2djoKTEYHib_-46zBOrHMdxO8QV59vdMLLB-Ba1bztOnPlIUOSfQVs-Vl38sbd5I1y39JTM82VzA9A5tO8ysC7dBd_tMX6qcllEHwHT2GUdbKXJrbIf9a5qJ8wVHe3gykjS9VcQ7EWM8N6pmvvDKxU5putUsZsZZyX4z8cR-ejN-QzNIv0vfCvZdk-ejg0-lHHOSYoxK6OVkl9RqH8dFo4FRamM2Pm17hU_moJjYxMowDTokxf-_kg76mnwmbvL0O87aZBAR8TAkQpoQNIrdtXAQosO2hkdgSWHFjoSk0G5-Uprc_R8bMiw-71eg_c1mGgUE65_OAn0bbvJ6AgyEN8i2-R0At9JfZajKS_hdKwG7NFjprFJHBkC9n6gzl3APUf4JfpYn9foRGK0BYR0vzWYWSK98I7sIQ7NAevXcrab0b6BEvxDGVb3PaGWlm-Swt9u9LDgUc2A_S7xKdjexaRcY04mIz9ifsCBWmBiJxZ3C2rDz4GXLfG9MB1KtRrH6EYB5TGQQStwBjli6-HtqQlxi3e6j2cMQ4j9ZavO_Tl1OGF02nEnJPVD3O5XEDXd4j8av3qN0tJSLrrefPd6fPPh3brf_lLCM-H8xnhRrgZ8yXa_9mBWriMtPFEoDY=s560-no?authuser=0
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec

theme: jekyll-theme-merlot
