title: Samuel Fernando
position: Data Analytics Engineer
affiliation: Blueshift Brasil
email: samuel.silva@blueshift.com.br
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?hl=en&user=chszpPcAAAAJ
github_link: https://github.com/samuelfernandofs
linkedin: https://www.linkedin.com/in/samuelfernando2030/
avatar: https://photos.app.goo.gl/SNRkaE8u4s3U3N59A 
google_analytics: UA-111540567-4
favicon: https://photos.app.goo.gl/SNRkaE8u4s3U3N59A
favicon_dark: https://photos.app.goo.gl/SNRkaE8u4s3U3N59A

