# Basic Information 
title: Samuel Fernando
position: Data Engineer Analyst
affiliation: Blueshift Brazil
affiliation_link: https://blueshift.com.br/
email: samuel.silva (at) outlook.com.br

# Search Engine Optimization (SEO)
keywords: samuel fernando, samuel, samuelfernando, samuel fernando
canonical: http://bio.samuelfernando.com.br/
description: Samuel Fernando is a Data Analytics Engineer Ph.D. candidate at University of Sao Paulo. His research lies in quantum computing, quantum finance, optimization.

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.co.uk/citations?hl=en&user=chszpPcAAAAJ
linkedin: https://www.linkedin.com/in/samuelfernando2030/
github_link: https://github.com/samuelfernandofs
twitter: https://mobile.twitter.com/samuelf78246883

# Images 
avatar: https://img.yliu.me/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/samuelfernandofs/samuel.fernando

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# General Data Protection Regulation (GDPR) information
# If you don't need to add the GDPR information, you may remove the following lines.
imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu
data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu?lang=en

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - CNAME
